CREATE TABLE T_CALENDAR(
 "CALENDAR_DATE" DATE NOT NULL,
 "WEEK_DAY" VARCHAR(20) NOT NULL,
 "WEEK_DAY_NUM" NUMERIC NOT NULL,
 "CALENDAR_YEAR" NUMERIC NOT NULL,
 "CALENDAR_MONTH" NUMERIC NOT NULL,
 "CALENDAR_DAY" NUMERIC NOT NULL,
 "IS_HOLIDAY" NUMERIC DEFAULT 0 NOT NULL,
 CONSTRAINT "T_CALENDAR_PK" PRIMARY KEY ("CALENDAR_DATE")
);

select * from  T_CALENDAR;
